---

###############################################################################
# Check list definition for each of the available verifiers
#
# <verifier_name>:
#   :auto: # list of automatically checked items
#     - automatically checked 1
#     - automatically checked 2
#     - ...
#   :manual: # list of checks which needs to be carried manually
#     - manually checked 1
#     - manually checked 2
#     - ...
###############################################################################

OnedVerifier:
  :auto:
    - Endpoint is reachable from the node were oneverify is executed
    - Authentication is properly set for oneadmin user
    - CLI is installed
  :manual:
    - Check OpenNebula version is correct
    - Check EE mirror are used
    - Check the mirror token is properly set
    - Port and IP for services is properly configured (check ports field)
    - Check FS space for database directory
    - Check DB cache configuration and FTS index cache
    - Services are enabled
    - Services starts and shutdown cleanly
    - Check logs to ensure scheduler can contact oned
    - Check VMs can contact OneGate
    - Check OneFlow commands (e.f oneflow list)
    - Restart the server and check that services are operational

SunstoneVerifier:
  :manual:
     - Check the right support token is used
     - Connect using 443 port to ensure proper SSL configuration
     - Check VNC/VMRC access is working as expected
     - Check every configured view
     - Check that zone can be switched (only for Federated environments)
     - Check Support Tab
     - Check import process work (only fro vCenter)

HostVerifier:
  :auto:
    - "reset check: turn host to offline and enable it back. The result will be OK if the host is properly set to OFFLINE state and back to MONITOR"
    - "monitoring timestamp check: check the monitoring timestamp is updated after 120s (default value)"
  :manual:
    - Check log state is MONITORED
    - Ensure all the checks are OK
    - Logs do not show Monitoring Host after the initial start
    - "Check VMs are monitored (tip: deploy a new VM, poweroff the VM from within the VM terminal, check the VM state is automatically set to POWEROFF)"
    - "Review monitor configuration attributes (tip: auto is not compatible with HA, VIP must be used)."
    - Deploy a VM at each host to ensure oneadmin have enough permissions
    - Check live migration (if needed)
    - Check Hypervisor configuration options (e.g virtio, caching, ...) (if needed)

VnetVerifier:
  :manual:
    - Check vCenter hooks configuration (if needed)
    - Test create/import/delete workflow for vCenter (if needed)
    - Check VM communication (the bridge is properly set). Check VM connectivity running on different hosts
    - Check MTU is the same for every node
    - SG works as expected (i.e check iptables rules)

ImageDatastoreVerifier:
  :manual:
    - Check right TM_MAD and DS_MAD are configured
    - Check both base path and real path are correct
    - Check BRIDGE_LIST (if needed)
    - Check right disk (i.e device) are used
    - Check system disk size + available storage
    - Check OpenNebula monitoring disk size + available storage
    - Check Images can be registered

SystemDatastoreVerifier:
  :auto:
    - "[LVM] VG is available on every host (if not an exception will be thrown)"
  :manual:
    - Check right TM_MAD and DS_MAD are configured
    - Check both base path and real path are correct
    - Check BRIDGE_LIST
    - Check right disk (i.e device) are used
    - Check system disk size + available storage
    - Check OpenNebula monitoring disk size + available storage
    - Ensure images are properly transferred to every host
    - "[LVM] Ensure enough space on DS folder (i.e metadata location)"
    - "[LVM] Ensure the VG have the right size on every host"
