---
###############################################################################
# Configuration attributes used by different verifiers
###############################################################################

# OpenNebula endpoint
:endpoint: 'http://localhost:2633/RPC2'

# Services default ports
:default_ports:
  :oneflow:    2474
  :onegate:    5030
  :sunstone:   9869
  :fireEdge:   2616
  :oned:       2633
  :monitord:   4124
  :apache:       80
  :apache_ssl:  443

# Check if the following units are enabled.
# If the name of the unit is the same for both distro families a string is enough.
# If the name defer between different distro families a different name can be
# provided for each distro family.
:enabled_units:
  - opennebula
  - opennebula-sunstone
  - opennebula-fireedge
  - opennebula-gate
  - opennebula-flow
  - :rhel: httpd
    :debian: apache2
