---
- name: Run core infrastucture verification test
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/core_services_verification.yml"
  when: run_core_services_verification

- name: Run network benchmarking
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/network_benchmark.yml"

