---
- when: (hostvars[groups[frontend_group | d('frontend')][0]]['ansible_host'] == ansible_host)
  block:
    - name: Run VM HA validation per cluster
      ansible.builtin.include_tasks: per_cluster.yml
      loop: "{{ _one_clusters }}"
      loop_control:
        loop_var: current_cluster
        label: "{{ current_cluster.name }}"
