---
- hosts: "{{ frontend_group | d('frontend') }}"
  tasks:
    # TODO: only on 1 frontend node if there is federation / HA
    - name: Get list of OpenNebula host IDs
      shell: onehost list -l ID --csv --no-header
      register: host_ids
      become: true
      become_user: oneadmin
      changed_when: false

    - name: Display all host IDs
      debug:
        msg: "Found OpenNebula hosts with IDs: {{ host_ids.stdout_lines }}"

    - name: Create a dedicated VM group for each host
      ansible.builtin.include_tasks: tasks/conn_matrix_per_host.yml
      loop: "{{ host_ids.stdout_lines }}"

#     - name: Cleanup all created VM groups
#       ansible.builtin.include_tasks: tasks/cleanup_conn_matrix_per_host.yml
#       loop: "{{ host_ids.stdout_lines }}"

- hosts: "{{ node_group | d('node') }}"
  gather_facts: true
  tasks:
    - name: Generate SSH key pair for conn-matrix
      ansible.builtin.command: ssh-keygen -t rsa -b 4096 -N "" -f $HOME/.ssh/conn-matrix -q
      args:
        creates: "{{ ansible_env.HOME }}/.ssh/conn-matrix"
    
    - name: Read public key
      ansible.builtin.slurp:
        src: "{{ ansible_env.HOME }}/.ssh/conn-matrix.pub"
      register: conn_matrix_pubkey_raw

    - name: Set fact with public key
      ansible.builtin.set_fact:
        conn_matrix_pubkey: "{{ conn_matrix_pubkey_raw['content'] | b64decode }}"

- name: Collect all public keys into a dictionary
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Build dictionary of node public keys
      ansible.builtin.set_fact:
        conn_matrix_pubkeys: >-
            {{
              dict(
                hostvars
                | dict2items
                | selectattr('value.conn_matrix_pubkey', 'defined')
                | map(attribute='value.ansible_host')
                | zip(
                    hostvars
                    | dict2items
                    | selectattr('value.conn_matrix_pubkey', 'defined')
                    | map(attribute='value.conn_matrix_pubkey')
                  )
              )
            }}

    # - name: ssh-keys
    #   debug:
    #     msg: |
    #       Public keys for conn-matrix:
    #       {% for host, key in conn_matrix_pubkeys.items() %}
    #       {{ host }}: {{ key }}
    #       {% endfor %}

- hosts: "{{ frontend_group | d('frontend') }}"
  tasks:
    - name: Deploy a VM on each host 
      ansible.builtin.include_tasks: tasks/conn_matrix_create_vms.yml
      loop: "{{ host_ids.stdout_lines }}"
