---
- hosts: all
  tasks:
    - name: Set playbook variables for Connectivity Matrix
      set_fact:
        _conn_matrix_bridge_name: "{{ conn_matrix_bridge_name | d('br-default') }}"
        _conn_matrix_ping_count: "{{ conn_matrix_ping_count | d(10) }}"
        _conn_matrix_vnet_name: "{{ conn_matrix_vnet_name | d('vnet-default') }}"
        # TODO: add a way to skip the whole conn_matrix if this is set to false. Right now it is always executed
        execute_conn_matrix: false

    - name: Set playbook variables for test VM
      set_fact:
        _test_vm_name: "{{ test_vm_name | d('Alpine Linux 3.21') }}"
        # NOTE: Optional parameters, can be overridden in the inventory file
        # test_vm_template_extra: |
        #    MEMORY=256

- ansible.builtin.import_playbook: ./prepare-test-vm-template.yml

- hosts: "{{ frontend_group | d('frontend') }}"
  roles:
    - role: test_vm
    - role: storage-benchmark

- ansible.builtin.import_playbook: ./conn-matrix.yml

- ansible.builtin.import_playbook: ./cleanup-test-vm-template.yml

# Will launch verification framework on the frontends
- hosts: "{{ frontend_group | d('frontend') }}"
  roles:
    - role: verification

# Run network tests on the hypervisor hosts
- hosts: "{{ node_group | d('node') }}"
  roles:
    - role: network-benchmark
