---
- name: Run test VM validation per cluster
  ansible.builtin.include_tasks:
    file: per_cluster.yml
  loop: "{{ _one_clusters }}"
  loop_control:
    loop_var: current_cluster
    label: "{{ current_cluster.name }}"
