---
ansible_python_interpreter: /usr/bin/python3

validation:
  # Check if OpenNebula services are running
  core_services: true
  # List of services to check enabled, stop and restart
  service_list:
    - name: opennebula.service
      desc: OpenNebula core (oned)
    - name: opennebula-gate.service
      desc: OpenNebula gate
    - name: opennebula-flow.service
      desc: OpenNebula flow
    - name: opennebula-scheduler.service
      desc: OpenNebula Scheduler
    - name: opennebula-fireedge.service
      desc: OpenNebula Fireedge GUI
  check_connection: true
  storage_benchmark: true
  create_vnet: true
  conn_matrix:
    bridge_name: br-test
    ping_count: 10
    vnet_name: VLAN_580
  vm:
    market_name: 'Alpine Linux 3.21'
    template_extra: |
      MEMORY="512"
  vnet:
    name: 'VLAN_580'
    desc: 'A test network for post-deployment cloud verification'
    bridge: 'br-test'
    vn_mad: 'dummy'
    phydev: ''
    network_address: '10.0.0.0'
    network_mask: '255.255.255.0'
    dns: '8.8.8.8'
    gateway: '10.0.0.1'
    ar:
      - type: "IP4"
        ip: '10.0.0.10'
        size: '10'

