---
_primary_frontend: "{{ groups[frontend_group | d('frontend')][0] }}"
_one_clusters: "{{ hostvars[_primary_frontend].one_clusters | d([]) }}"
_one_clusters_multi: "{{ hostvars[_primary_frontend].one_clusters_multi | d(false) }}"
_test_vm_template_image_ids_map: "{{ hostvars[_primary_frontend].test_vm_template_image_ids | d({}) }}"
